- name: git
  hosts: web
  become: true # it takes sudo access, in sudo only packages gets installed ; root access
  tasks: 
  - name: install git
    ansible.builtin.git:
        name: git
        state: present