- name: devops course information
  hosts: local
  connection: local
  vars:
      course: "devops with aws" # string
      duration: 120hrs
      topics: #list
      - linux
      - shell
      - ansible
      - terraform
      - aws
      - k8
      live: true #boolean
      tools: #map/dict
          ci: jenkins
          cm: ansible
          cloud: aws
  tasks:
  - name: print the information
    ansible.builtin.debug:
        msg: " hi i am learning {{course}}, duration is {{duration}} , topics are {{topics}} , live : {{live}} , tools are {{tools}}"