- name: check a number is less than 10 or not
hosts: web
vars_prompt:
- name: number
  prompt: please enter the number
  private: false
tasks:
- name: print this if less than 10
  ansible.builtin.debug:
      msg: "given number is {{ number }} is less than 10"
  when: number  < 10 # conditional expression 


- name: print this if greater than 10
  ansible.builtin.debug:
      msg: "given number is {{ number }} is greater than or equal to 10"
  when: number >= 10 