# to install packages

- name: loops demo
  hosts: web
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.dnf: 
        #msg: "{{item}}"
        state: present
    loop:
    - mysql
    - nginx
    - postfix
    - postgresql

  - name: Check if a package is installed
    ansible.builtin.dnf:
        name: mysql
        state: present

  - name: Check if a package is installed
    ansible.builtin.dnf:
        name: postgresql
        state: present