# to install packages

- name: loops demo
  hosts: web
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.dnf: 
        #msg: "{{item}}"
        name: "{{item.name}}"
        state: "{{item.state}}"
    loop:
    - { name: 'mysql' , state: 'present'}
    - { name: 'nginx' , state: 'present'}
    - { name: 'postfix' , state: 'present'}
    - { name: 'postgresql' , state: 'absent'}