- name: demo on filters / functions
  hosts: web
  become: yes
  connection: web
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
        msg: "Hello {{ course | default('Ansible')}}"
