- name: demo on filters / functions
  hosts: local
  #become: yes
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
        msg: "Hello {{ course | default('Ansible')}}"

  - name: convert to upper case
    vars:
        greeting: " Hello Akhila"
    ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

  - name: convert to lower case
    vars:
        greeting: " Hello Akhila"
    ansible.builtin.debug:
        msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
        numbers: [1,2,3,4,3,4,5,6,8]
    ansible.builtin.debug:
        msg: " {{ numbers | unique }}"

  - name: get the minimum and maximum
    vars:
        numbers: [1,2,3,4,3,4,5,6,8]
    ansible.builtin.debug:
        msg: "Min: {{ numbers|  min }} , Max: {{ numbers|  max }}"
