- name: demo on filters / functions
  hosts: local
  #become: yes
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
        msg: "Hello {{ course | default('Ansible')}}"

  - name: convert to upper case
    vars:
        greeting: " Hello Akhila"
    ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

   - name: convert to lower case
    vars:
        greeting: " Hello Akhila"
    ansible.builtin.debug:
        msg: "{{ greeting | lower }}"
