- name: demo on filters / functions
  hosts: local
  #become: yes
  connection: local
  - name: print the default variable
    ansible.builtin.debug:
        msg: "Hello {{ course | default('Ansible')}}"
